events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>[0-9]+)/$', views.event_detail, name='event_detail'),
    url(r'^new/$', views.event_update, name='event_update'),
]

members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>[0-9]+)/$', views.member_detail, name='member_detail'),
]

yfcdb4/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from yfcdb4 import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^members/', include('members.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^$', views.index),
]

events/models.py
from django.db import models
from members.models import Member
from django.core.urlresolvers import reverse

EVENT_TYPE = (
    ("CA", "Chapter Assembly"),
    ("PF", "Pastoral Formation"),
    ("YC", "Youth Camp"),
    ("HH", "Household"),
    ("Cf", "Conference"),
    ("Ka", "Kassanga"),
    ("SM", "Service Meeting"),
)

ROLE = (
    ('P', 'Present'),
    ('Spk', 'Speaker'),
    ('Shr', 'Sharer'),
    ('Hhl', 'Household Leader'),
    ('ST', 'Service Team'),
    ('TL', 'Team Leader'),
    ('ATL', 'Assistant Team Leader'),
    ('HS', 'Head Servant'),
    ('AHS', 'Assistant Head Servant'),
    ('PW', 'Prayer Warrior'),
    ('FC', 'Food Committee'),
    ('MM', 'Music Ministry'),
)

class Event(models.Model):
    #names
    date = models.DateField()
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=2, choices=EVENT_TYPE)
    venue = models.CharField(max_length=50)
    attendees = models.ManyToManyField(
        Member,
        through='Attend',
        through_fields=('event', 'member'),
    )

    def __str__(self):
        return ("%s: %s at %s" % (self.date, self.name, self.venue))

    def get_absolute_url(self):
        return reverse('events:event_index')

class Attend(models.Model):
    #names
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    role = models.CharField(max_length=3, choices=ROLE)

    def __str__(self):
        return ("%s %s attended %s" % (self.member.nickname, self.member.family_name, self.event.name))

members/models.py
from django.db import models

BLOOD_TYPE = (
    ('B+', 'B+'),
)

GENDER = (
    ('m', 'Male'),
    ('f', 'Female'),
)

class Member(models.Model):
    #names
    family_name = models.CharField(max_length=100)
    given_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    nickname = models.CharField(max_length=100, blank=True)
    #address
    address_st = models.CharField(max_length=200)
    address_village = models.CharField(max_length=200)
    address_city = models.CharField(max_length=200)
    #birthday
    birthday = models.DateField(blank=True)
    #other
    kfc_to_yfc = models.BooleanField(default=False)
    school = models.CharField(max_length=100)
    school_level = models.CharField(max_length=10)
    course = models.CharField(max_length=100, blank=True)
    blood_type = models.CharField(max_length=2, choices=BLOOD_TYPE,blank=True)
    gender = models.CharField(max_length=1, choices=GENDER)
    cell_number = models.CharField(max_length=11)
    email = models.EmailField(max_length=50)
    #parents
    name_of_father = models.CharField(max_length=100)
    fathers_occupation = models.CharField("Father's occupation", max_length=100, blank=True)
    fathers_contact_details = models.CharField("Father's cell #", max_length=100, blank=True)
    name_of_mother = models.CharField(max_length=100)
    mothers_occupation = models.CharField("Mother's occupation", max_length=100, blank=True)
    mothers_contact_details = models.CharField("Mother's cell #", max_length=100, blank=True)
    #other
    special_skills = models.CharField(
        max_length=100, blank=True,
        help_text="(eg playing musical instruments, dancing, singing, etc)",
    )
    illness = models.CharField(
        max_length=100, blank=True,
        help_text="Illnesses that require special attention",
    )

    def __str__(self):
        return ("%s, %s '%s' %s" % (self.family_name, self.given_name, self.nickname, self.middle_name))

events/forms.py
from django import forms

from members.models import Member
from .models import EVENT_TYPE, ROLE

class EventForm(forms.Form):
    date = forms.DateField(
        input_formats=[
            '%m/%d/%Y',
            '%m/%d/%y'
        ],
        help_text="format: mm/dd/yy or mm/dd/yyyy"
    )
    name = forms.CharField(max_length=100)
    type = forms.ChoiceField(choices=EVENT_TYPE)
    venue = forms.CharField(max_length=50)

events/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import generic

from events.forms import EventForm
from members.models import Member
from .models import Event, Attend, ROLE


def index(request):
    events = Event.objects.all()

    context = {
        'events': events,
    }

    return render(request, 'events/event_index.html', context)

class DetailView(generic.DetailView):
    model = Event
    template_name = 'polls/event_detail.html'

def event_detail(request, id):
    event = get_object_or_404(Event, pk=id)
    attendees = Attend.objects.filter(event=event.id)

    context = {
        'event': event,
        'attendees': attendees,
    }

    return render(request, 'events/event_detail.html', context)


def event_update(request):
    members = Member.objects.all()

    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EventForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            date = form.cleaned_data['date']
            type = form.cleaned_data['type']
            name = form.cleaned_data['name']
            venue = form.cleaned_data['venue']
            new_event = Event(date=date, type=type, name=name, venue=venue)
            new_event.save()
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect(new_event.get_absolute_url())

    # if a GET (or any other method) we'll create a blank form
    else:
        form = EventForm()

    context = {
        'form': form,
        'members': members,
        'roles': ROLE,
    }

    return render(request, 'events/event_update.html', context)

members/views.py
from django.shortcuts import render
from .models import Member


def index(request):
    members = Member.objects.all()

    context = {
        'members': members,
    }

    return render(request, 'members/member_index.html', context)

def member_detail(request, id):
    member = Member.objects.get(pk=id)

    context = {
        'member': member,
    }

    return render(request, 'members/member_detail.html', context)

yfcdb4/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

bootstrapform/templates/bootstrapform/field.html
{% load bootstrap %}

<div class="form-group{% if field.errors %} has-error{% endif %}">
    {% if field|is_checkbox %}
        <div class="{{ classes.single_value }}">
            <div class="checkbox">
                {% if field.auto_id %}
                    <label {% if field.field.required and form.required_css_class %}class="{{ form.required_css_class }}"{% endif %}>
                        {{ field }} <span>{{ field.label }}</span>
                    </label>
                {% endif %}
                {% for error in field.errors %}
                    <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                {% endfor %}

                {% if field.help_text %}
                    <p class="help-block">
                        {{ field.help_text|safe }}
                    </p>
                {% endif %}
            </div>
        </div>
    {% elif field|is_radio %}
        {% if field.auto_id %}
            <label class="control-label {{ classes.label }} {% if field.field.required %}{{ form.required_css_class }}{% endif %}">{{ field.label }}</label>
        {% endif %}
        <div class="{{ classes.value }}">
            {% for choice in field %}
                <div class="radio">
                    <label>
                        {{ choice.tag }}
                        {{ choice.choice_label }}
                    </label>
                </div>
            {% endfor %}

            {% for error in field.errors %}
                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
            {% endfor %}

            {% if field.help_text %}
            <p class="help-block">
                {{ field.help_text|safe }}
            </p>
            {% endif %}
        </div>
    {% else %}
        {% if field.auto_id %}
            <label class="control-label {{ classes.label }} {% if field.field.required %}{{ form.required_css_class }}{% endif %}" for="{{ field.auto_id }}">{{ field.label }}</label>
        {% endif %}

        <div class="{{ classes.value }} {% if field|is_multiple_checkbox %}multiple-checkbox{% endif %}">
            {{ field }}

            {% for error in field.errors %}
                <span class="help-block {{ form.error_css_class }}">{{ error }}</span>
                {% endfor %}

            {% if field.help_text %}
                <p class="help-block">
                    {{ field.help_text|safe }}
                </p>
            {% endif %}
        </div>
    {% endif %}
</div>

bootstrapform/templates/bootstrapform/form.html
{% if form.non_field_errors %}
    <div class="alert alert-danger">
        <a class="close" data-dismiss="alert">&times;</a>
        {% for non_field_error in form.non_field_errors %}
             {{ non_field_error }}
        {% endfor %}
    </div>
{% endif %}

{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
    {% include 'bootstrapform/field.html' %}
{% endfor %}

bootstrapform/templates/bootstrapform/formset.html
{{ formset.management_form }}

{% for form in formset %}
  {% if classes.label == 'sr-only' %}
      <div class="form-inline">
      {% include "bootstrapform/form.html" with form=form %}
      </div>
  {%else%}
      {% include "bootstrapform/form.html" with form=form %}
  {% endif %}
{% endfor %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>YFC</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">YFC</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'members:index' %}">Members<span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'events:index' %}">Events</a></li>
          </ul>
          <form class="navbar-form navbar-left" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Login</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- CONTENT -->
    {% block content %}
    {% endblock %}



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/events/event_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Event</h1>
    </div>
    <div class="col-md-6 col-sm-6">
        Name: {{ event.name }}
        <br>
        Date: {{ event.date }}
        <br>
        Venue: {{ event.venue }}
        <br>
    </div>
    <div class="col-md-6 col-sm-6">
        Attendees  <span class="badge">{{ attendees|length }}</span>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Role</td>
                </tr>
            </thead>
            <tbody>
                {% for attendee in attendees %}
                <tr>
                    <td>{{ attendee.member.nickname }} {{ attendee.member.family_name }}</td>
                    <td>{{ attendee.role }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/events/event_index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Events list</h1>
    </div>
    <div class="list-group">
        {% for event in events %}
        <a href="{% url 'events:event_detail' event.id %}" class="list-group-item">
            <span class="badge">{{ event.attendees.all|length }}</span>
            {{ event.name }}
        </a>
        {% endfor %}
    </div>
    <a class="btn btn-primary" href="{% url 'events:event_update' %}" role="button">New event</a>
</div>
{% endblock %}

templates/events/event_update.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block content %}
<div class="container">
    <div class="col-md-6 col-sm-6">
        <form class="form-horizontal" method="post">
            <legend>Event</legend>
            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
            <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-6 col-sm-6">
        <legend>Attendees</legend>
        <table class="table table-hover">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Role</td>
                </tr>
            </thead>
            <tbody>
                {% for member in members %}
                <tr>
                    <td>{{ member.nickname }} {{ member.family_name }}</td>
                    <td>
                        <select class="form-control">
                            {% for role in roles %}
                            <option>{{ role }}</option>
                            {% endfor %}
                        </select>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
    <div class="container">
        <h1>YFC</h1>
        <p>Chapter C</p>
    </div>
</div>
{% endblock %}

templates/members/member_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Member</h1>
    </div>
    <div class="col-md-6 col-sm-6">
        Name: {{ member.family_name }}, {{ member.given_name }} {{ member.middle_name }}
        <br>
        Preferred name: {{ member.nickname }}
        <br>

    </div>
</div>
{% endblock %}

templates/members/member_index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="page-header">
      <h1>Members list</h1>
    </div>
    <div class="list-group">
        {% for member in members %}
        <a href="{% url 'members:member_detail' member.id %}" class="list-group-item">{{ member.nickname }} {{ member.family_name }}</a>
        {% endfor %}
    </div>
</div>
{% endblock content %}